name: Build
run-name: Build on ${{ github.sha }}

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref || github.ref_name }}
        repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

    - name: Set up JDK 19
      uses: actions/setup-java@v4
      with:
        java-version: '19'
        distribution: 'temurin'

    - name: Build
      run: |
        chmod +x gradlew
        ./gradlew build -x verifyGoogleJavaFormat
